### ISSUE TITLE
Add favicon to browser header

### ISSUE THREAD

**Issue by sangjunp4rk** [Comicmaniac/tea-cozy#2]
Don't forget to put a favicon! This is the small icon on your browser tab. You can add `<link rel="icon" href="http://example.com/favicon.png">` to you `<head>` element. It’s a small detail but helps your website look more complete!

https://github.com/Comicmaniac/tea-cozy/blob/master/index.html#L3

**Comment by Comicmaniac** [comment]
Oh, thank you for that! I've missed this information in the course. 
And indeed, a favicon makes the page much faster to find between different tabs.
